### ISSUE TITLE
[Recommend] Add some references resources

### ISSUE THREAD

**Issue by wang1212** [Dreams-d/Algorithm#3]
There are already many code implementations of the algorithm, but not many people can do optimization.

Therefore, I think that for many people, it is more important to understand the core idea of the algorithm than to implement it in code. I make some suggestions：

- **Add some references below each algorithm, such as articles discussing related algorithms.**
  - The content of the article should be as **concise and interesting as possible, easy to understand**, not like school textbooks
  - The best part is that it can be accompanied by **some animations**, it is always easier for people to understand visual things.

**Comment by Loading-m** [comment]
very good suggestion，which will be added to our plan. At the same time, we will simulate the process with the implementation code to ensure that most people have a clearer understanding of the implementation ideas！

thank you suggestion,We also look forward to your further supplement
